[package]
name = "kairos"
version = "0.4.0"
description = "Kairos — cross-platform time management desktop app"
authors = ["mikoto"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "kairos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls", "blocking", "stream", "gzip"], default-features = false }
futures-util = "0.3"
tokio = { version = "1", features = ["rt"] }
aes = "0.8"
cbc = "0.1"
hex = "0.4"
md5 = "0.7"
quick-xml = "0.37"
dotenvy = "0.15"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-notification = "2.3.2"
uuid = { version = "1", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
tauri-winrt-notification = "0.7.2"
windows-registry = "0.5.3"
