pub mod briefing;
pub mod courses;
pub mod exams;
pub mod lzu;
pub mod notifications;
pub mod pomodoro;
pub mod schedule;
pub mod sync;
pub mod tasks;
#[cfg(not(target_os = "android"))]
pub mod widget;
