// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applySyncedAiConfig = `-- name: ApplySyncedAiConfig :exec
UPDATE ai_config
SET enabled = $1,
    base_url = $2,
    model = $3,
    api_key_encrypted = $4,
    updated_at = $5
WHERE id = 1
`

type ApplySyncedAiConfigParams struct {
	Enabled         bool
	BaseUrl         string
	Model           string
	ApiKeyEncrypted string
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ApplySyncedAiConfig(ctx context.Context, arg ApplySyncedAiConfigParams) error {
	_, err := q.db.Exec(ctx, applySyncedAiConfig,
		arg.Enabled,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyEncrypted,
		arg.UpdatedAt,
	)
	return err
}

const getAiConfig = `-- name: GetAiConfig :one
SELECT id, enabled, base_url, model, api_key_encrypted, sync_enabled, created_at, updated_at FROM ai_config
WHERE id = 1
`

func (q *Queries) GetAiConfig(ctx context.Context) (AiConfig, error) {
	row := q.db.QueryRow(ctx, getAiConfig)
	var i AiConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEncrypted,
		&i.SyncEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMorningBrief = `-- name: GetMorningBrief :one
SELECT id, date, markdown, source, model, generated_at, created_at, updated_at FROM ai_morning_brief
WHERE date = $1
`

func (q *Queries) GetMorningBrief(ctx context.Context, date pgtype.Date) (AiMorningBrief, error) {
	row := q.db.QueryRow(ctx, getMorningBrief, date)
	var i AiMorningBrief
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Markdown,
		&i.Source,
		&i.Model,
		&i.GeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAiConfig = `-- name: UpdateAiConfig :exec
UPDATE ai_config
SET enabled = $1,
    base_url = $2,
    model = $3,
    api_key_encrypted = $4,
    sync_enabled = $5,
    updated_at = now()
WHERE id = 1
`

type UpdateAiConfigParams struct {
	Enabled         bool
	BaseUrl         string
	Model           string
	ApiKeyEncrypted string
	SyncEnabled     bool
}

func (q *Queries) UpdateAiConfig(ctx context.Context, arg UpdateAiConfigParams) error {
	_, err := q.db.Exec(ctx, updateAiConfig,
		arg.Enabled,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyEncrypted,
		arg.SyncEnabled,
	)
	return err
}

const upsertMorningBrief = `-- name: UpsertMorningBrief :one
INSERT INTO ai_morning_brief (
    date,
    markdown,
    source,
    model,
    generated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (date) DO UPDATE SET
    markdown = EXCLUDED.markdown,
    source = EXCLUDED.source,
    model = EXCLUDED.model,
    generated_at = EXCLUDED.generated_at,
    updated_at = now()
RETURNING id, date, markdown, source, model, generated_at, created_at, updated_at
`

type UpsertMorningBriefParams struct {
	Date        pgtype.Date
	Markdown    string
	Source      string
	Model       string
	GeneratedAt pgtype.Timestamptz
}

func (q *Queries) UpsertMorningBrief(ctx context.Context, arg UpsertMorningBriefParams) (AiMorningBrief, error) {
	row := q.db.QueryRow(ctx, upsertMorningBrief,
		arg.Date,
		arg.Markdown,
		arg.Source,
		arg.Model,
		arg.GeneratedAt,
	)
	var i AiMorningBrief
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Markdown,
		&i.Source,
		&i.Model,
		&i.GeneratedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
