// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourseImportDuplicates = `-- name: CountCourseImportDuplicates :one
SELECT count(*)
FROM courses
WHERE deleted_at IS NULL
  AND semester = $1
  AND name = $2
  AND day_of_week = $3
  AND start_time = $4
  AND end_time = $5
  AND week_pattern = $6
  AND semester_start_date IS NOT DISTINCT FROM $7
  AND location = $8
  AND teacher = $9
`

type CountCourseImportDuplicatesParams struct {
	Semester          string
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	WeekPattern       string
	SemesterStartDate pgtype.Date
	Location          string
	Teacher           string
}

func (q *Queries) CountCourseImportDuplicates(ctx context.Context, arg CountCourseImportDuplicatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseImportDuplicates,
		arg.Semester,
		arg.Name,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.SemesterStartDate,
		arg.Location,
		arg.Teacher,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    sync_id,
    name,
    day_of_week,
    start_time,
    end_time,
    week_pattern,
    semester_start_date,
    location,
    teacher,
    color,
    semester
) VALUES (
    COALESCE(NULLIF($1::text, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, sync_id, name, day_of_week, start_time, end_time, location, teacher, color, semester, week_pattern, semester_start_date, deleted_at, created_at, updated_at
`

type CreateCourseParams struct {
	SyncID            string
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	WeekPattern       string
	SemesterStartDate pgtype.Date
	Location          string
	Teacher           string
	Color             string
	Semester          string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.SyncID,
		arg.Name,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.SemesterStartDate,
		arg.Location,
		arg.Teacher,
		arg.Color,
		arg.Semester,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Teacher,
		&i.Color,
		&i.Semester,
		&i.WeekPattern,
		&i.SemesterStartDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, sync_id, name, day_of_week, start_time, end_time, location, teacher, color, semester, week_pattern, semester_start_date, deleted_at, created_at, updated_at FROM courses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Teacher,
		&i.Color,
		&i.Semester,
		&i.WeekPattern,
		&i.SemesterStartDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCoursesForSync = `-- name: ListAllCoursesForSync :many
SELECT id, sync_id, name, day_of_week, start_time, end_time, location, teacher, color, semester, week_pattern, semester_start_date, deleted_at, created_at, updated_at FROM courses
ORDER BY id ASC
`

func (q *Queries) ListAllCoursesForSync(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listAllCoursesForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Teacher,
			&i.Color,
			&i.Semester,
			&i.WeekPattern,
			&i.SemesterStartDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, sync_id, name, day_of_week, start_time, end_time, location, teacher, color, semester, week_pattern, semester_start_date, deleted_at, created_at, updated_at FROM courses
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR semester = $1::text)
ORDER BY day_of_week ASC, start_time ASC, id ASC
`

func (q *Queries) ListCourses(ctx context.Context, semester pgtype.Text) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Name,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Teacher,
			&i.Color,
			&i.Semester,
			&i.WeekPattern,
			&i.SemesterStartDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCourse = `-- name: SoftDeleteCourse :exec
UPDATE courses
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteCourse, id)
	return err
}

const updateAllCoursesSemesterStartDate = `-- name: UpdateAllCoursesSemesterStartDate :execrows
UPDATE courses
SET semester_start_date = $1, updated_at = now()
WHERE deleted_at IS NULL
`

func (q *Queries) UpdateAllCoursesSemesterStartDate(ctx context.Context, semesterStartDate pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, updateAllCoursesSemesterStartDate, semesterStartDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET name = $1,
    day_of_week = $2,
    start_time = $3,
    end_time = $4,
    week_pattern = $5,
    semester_start_date = $6,
    location = $7,
    teacher = $8,
    color = $9,
    semester = $10,
    updated_at = now()
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, sync_id, name, day_of_week, start_time, end_time, location, teacher, color, semester, week_pattern, semester_start_date, deleted_at, created_at, updated_at
`

type UpdateCourseParams struct {
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	WeekPattern       string
	SemesterStartDate pgtype.Date
	Location          string
	Teacher           string
	Color             string
	Semester          string
	ID                int64
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Name,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.SemesterStartDate,
		arg.Location,
		arg.Teacher,
		arg.Color,
		arg.Semester,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Name,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Teacher,
		&i.Color,
		&i.Semester,
		&i.WeekPattern,
		&i.SemesterStartDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
