// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExamImportDuplicates = `-- name: CountExamImportDuplicates :one
SELECT count(*)
FROM exams
WHERE deleted_at IS NULL
  AND semester = $1
  AND course_name = $2
  AND exam_datetime = $3
  AND exam_end_datetime IS NOT DISTINCT FROM $4
  AND location = $5
`

type CountExamImportDuplicatesParams struct {
	Semester        string
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
}

func (q *Queries) CountExamImportDuplicates(ctx context.Context, arg CountExamImportDuplicatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExamImportDuplicates,
		arg.Semester,
		arg.CourseName,
		arg.ExamDatetime,
		arg.ExamEndDatetime,
		arg.Location,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExam = `-- name: CreateExam :one
INSERT INTO exams (
    sync_id,
    course_name,
    exam_datetime,
    exam_end_datetime,
    location,
    notes,
    course_id,
    semester
) VALUES (
    COALESCE(NULLIF($1::text, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester, deleted_at, created_at, updated_at
`

type CreateExamParams struct {
	SyncID          string
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
	Notes           string
	CourseID        pgtype.Int8
	Semester        string
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, createExam,
		arg.SyncID,
		arg.CourseName,
		arg.ExamDatetime,
		arg.ExamEndDatetime,
		arg.Location,
		arg.Notes,
		arg.CourseID,
		arg.Semester,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CourseName,
		&i.ExamDatetime,
		&i.ExamEndDatetime,
		&i.Location,
		&i.Notes,
		&i.CourseID,
		&i.Semester,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExam = `-- name: GetExam :one
SELECT id, sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester, deleted_at, created_at, updated_at FROM exams
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetExam(ctx context.Context, id int64) (Exam, error) {
	row := q.db.QueryRow(ctx, getExam, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CourseName,
		&i.ExamDatetime,
		&i.ExamEndDatetime,
		&i.Location,
		&i.Notes,
		&i.CourseID,
		&i.Semester,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExamsForSync = `-- name: ListAllExamsForSync :many
SELECT id, sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester, deleted_at, created_at, updated_at FROM exams
ORDER BY id ASC
`

func (q *Queries) ListAllExamsForSync(ctx context.Context) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listAllExamsForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exam{}
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.CourseName,
			&i.ExamDatetime,
			&i.ExamEndDatetime,
			&i.Location,
			&i.Notes,
			&i.CourseID,
			&i.Semester,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExams = `-- name: ListExams :many
SELECT id, sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester, deleted_at, created_at, updated_at FROM exams
WHERE deleted_at IS NULL
ORDER BY exam_datetime ASC, id ASC
`

func (q *Queries) ListExams(ctx context.Context) ([]Exam, error) {
	rows, err := q.db.Query(ctx, listExams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exam{}
	for rows.Next() {
		var i Exam
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.CourseName,
			&i.ExamDatetime,
			&i.ExamEndDatetime,
			&i.Location,
			&i.Notes,
			&i.CourseID,
			&i.Semester,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExam = `-- name: SoftDeleteExam :exec
UPDATE exams
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteExam(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteExam, id)
	return err
}

const updateExam = `-- name: UpdateExam :one
UPDATE exams
SET course_name = $1,
    exam_datetime = $2,
    exam_end_datetime = $3,
    location = $4,
    notes = $5,
    course_id = $6,
    semester = $7,
    updated_at = now()
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester, deleted_at, created_at, updated_at
`

type UpdateExamParams struct {
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
	Notes           string
	CourseID        pgtype.Int8
	Semester        string
	ID              int64
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) (Exam, error) {
	row := q.db.QueryRow(ctx, updateExam,
		arg.CourseName,
		arg.ExamDatetime,
		arg.ExamEndDatetime,
		arg.Location,
		arg.Notes,
		arg.CourseID,
		arg.Semester,
		arg.ID,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.CourseName,
		&i.ExamDatetime,
		&i.ExamEndDatetime,
		&i.Location,
		&i.Notes,
		&i.CourseID,
		&i.Semester,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
