// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiConfig struct {
	ID              int64
	Enabled         bool
	BaseUrl         string
	Model           string
	ApiKeyEncrypted string
	SyncEnabled     bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AiMorningBrief struct {
	ID          int64
	Date        pgtype.Date
	Markdown    string
	Source      string
	Model       string
	GeneratedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Course struct {
	ID                int64
	SyncID            pgtype.Text
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	Location          string
	Teacher           string
	Color             string
	Semester          string
	WeekPattern       string
	SemesterStartDate pgtype.Date
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Exam struct {
	ID              int64
	SyncID          pgtype.Text
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
	Notes           string
	CourseID        pgtype.Int8
	Semester        string
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type NotificationConfig struct {
	ID          int64
	Enabled     bool
	ExamOffsets []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PomodoroConfig struct {
	ID                      int64
	WorkSeconds             int32
	ShortBreakSeconds       int32
	LongBreakSeconds        int32
	SessionsBeforeLongBreak int32
	AutoStartNextPhase      bool
}

type PomodoroProfile struct {
	ID                      int64
	Name                    string
	WorkSeconds             int32
	ShortBreakSeconds       int32
	LongBreakSeconds        int32
	SessionsBeforeLongBreak int32
	IsBuiltin               bool
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type PomodoroRuntimeState struct {
	ID               int64
	Phase            string
	RemainingSeconds int32
	TotalSeconds     int32
	IsRunning        bool
	ActiveSessionID  pgtype.Int8
	DateKey          pgtype.Date
	LastSeenAt       pgtype.Timestamptz
	Interrupted      bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PomodoroSession struct {
	ID          int64
	SyncID      pgtype.Text
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	SessionType string
	TaskID      pgtype.Int8
	DeletedAt   pgtype.Timestamptz
}

type SemesterContext struct {
	ID           int64
	Source       string
	AcademicYear pgtype.Text
	Term         pgtype.Text
	TermLabel    string
	StartDate    pgtype.Date
	CurrentWeek  pgtype.Int4
	TotalWeeks   pgtype.Int4
	RefreshedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type SyncConfig struct {
	ID                   int64
	ServerUrl            string
	Username             string
	Password             string
	AutoSync             bool
	LastSyncAt           pgtype.Timestamptz
	RemoteEtag           pgtype.Text
	DeviceID             pgtype.Text
	DatasetID            pgtype.Text
	AiSettingsRemoteEtag pgtype.Text
}

type Task struct {
	ID                int64
	SyncID            pgtype.Text
	Title             string
	Description       string
	Status            string
	Priority          string
	DueDate           pgtype.Date
	Tags              []byte
	RemindAt          pgtype.Timestamptz
	ReminderTime      pgtype.Time
	IsDaily           bool
	LastCompletedDate pgtype.Date
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type TermPhase struct {
	ID                       int64
	SyncID                   pgtype.Text
	TermLabel                string
	PhaseType                string
	StartWeek                int32
	EndWeek                  int32
	AffectsCourses           bool
	AffectsExamNotifications bool
	PomodoroProfile          string
	NotificationRules        []byte
	SortOrder                int32
	DeletedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}
