// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package store

import (
	"context"
)

const getNotificationConfig = `-- name: GetNotificationConfig :one
SELECT id, enabled, exam_offsets, created_at, updated_at FROM notification_config
WHERE id = 1
`

func (q *Queries) GetNotificationConfig(ctx context.Context) (NotificationConfig, error) {
	row := q.db.QueryRow(ctx, getNotificationConfig)
	var i NotificationConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.ExamOffsets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationConfig = `-- name: UpdateNotificationConfig :exec
UPDATE notification_config
SET enabled = $1,
    exam_offsets = $2,
    updated_at = now()
WHERE id = 1
`

type UpdateNotificationConfigParams struct {
	Enabled     bool
	ExamOffsets []byte
}

func (q *Queries) UpdateNotificationConfig(ctx context.Context, arg UpdateNotificationConfigParams) error {
	_, err := q.db.Exec(ctx, updateNotificationConfig, arg.Enabled, arg.ExamOffsets)
	return err
}
