// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pomodoro.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearRuntimeInterruption = `-- name: ClearRuntimeInterruption :exec
UPDATE pomodoro_runtime_state
SET interrupted = false, updated_at = now()
WHERE id = 1
`

func (q *Queries) ClearRuntimeInterruption(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearRuntimeInterruption)
	return err
}

const countCompletedWorkSessions = `-- name: CountCompletedWorkSessions :one
SELECT count(*)
FROM pomodoro_sessions
WHERE session_type = 'work'
  AND ended_at IS NOT NULL
  AND deleted_at IS NULL
  AND started_at >= $1
  AND started_at < $2
`

type CountCompletedWorkSessionsParams struct {
	WindowStart pgtype.Timestamptz
	WindowEnd   pgtype.Timestamptz
}

func (q *Queries) CountCompletedWorkSessions(ctx context.Context, arg CountCompletedWorkSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedWorkSessions, arg.WindowStart, arg.WindowEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPomodoroProfile = `-- name: CreatePomodoroProfile :one
INSERT INTO pomodoro_profiles (
    name,
    work_seconds,
    short_break_seconds,
    long_break_seconds,
    sessions_before_long_break,
    is_builtin
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    false
)
RETURNING id, name, work_seconds, short_break_seconds, long_break_seconds, sessions_before_long_break, is_builtin, created_at, updated_at
`

type CreatePomodoroProfileParams struct {
	Name                    string
	WorkSeconds             int32
	ShortBreakSeconds       int32
	LongBreakSeconds        int32
	SessionsBeforeLongBreak int32
}

func (q *Queries) CreatePomodoroProfile(ctx context.Context, arg CreatePomodoroProfileParams) (PomodoroProfile, error) {
	row := q.db.QueryRow(ctx, createPomodoroProfile,
		arg.Name,
		arg.WorkSeconds,
		arg.ShortBreakSeconds,
		arg.LongBreakSeconds,
		arg.SessionsBeforeLongBreak,
	)
	var i PomodoroProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkSeconds,
		&i.ShortBreakSeconds,
		&i.LongBreakSeconds,
		&i.SessionsBeforeLongBreak,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPomodoroSession = `-- name: CreatePomodoroSession :one
INSERT INTO pomodoro_sessions (
    sync_id,
    started_at,
    session_type,
    task_id
) VALUES (
    COALESCE(NULLIF($1::text, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4
)
RETURNING id, sync_id, started_at, ended_at, session_type, task_id, deleted_at
`

type CreatePomodoroSessionParams struct {
	SyncID      string
	StartedAt   pgtype.Timestamptz
	SessionType string
	TaskID      pgtype.Int8
}

func (q *Queries) CreatePomodoroSession(ctx context.Context, arg CreatePomodoroSessionParams) (PomodoroSession, error) {
	row := q.db.QueryRow(ctx, createPomodoroSession,
		arg.SyncID,
		arg.StartedAt,
		arg.SessionType,
		arg.TaskID,
	)
	var i PomodoroSession
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.StartedAt,
		&i.EndedAt,
		&i.SessionType,
		&i.TaskID,
		&i.DeletedAt,
	)
	return i, err
}

const createRuntimeState = `-- name: CreateRuntimeState :one
INSERT INTO pomodoro_runtime_state (
    id,
    date_key,
    last_seen_at
) VALUES (
    1,
    $1,
    now()
)
RETURNING id, phase, remaining_seconds, total_seconds, is_running, active_session_id, date_key, last_seen_at, interrupted, created_at, updated_at
`

func (q *Queries) CreateRuntimeState(ctx context.Context, dateKey pgtype.Date) (PomodoroRuntimeState, error) {
	row := q.db.QueryRow(ctx, createRuntimeState, dateKey)
	var i PomodoroRuntimeState
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.RemainingSeconds,
		&i.TotalSeconds,
		&i.IsRunning,
		&i.ActiveSessionID,
		&i.DateKey,
		&i.LastSeenAt,
		&i.Interrupted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePomodoroProfile = `-- name: DeletePomodoroProfile :exec
DELETE FROM pomodoro_profiles
WHERE id = $1 AND is_builtin = false
`

func (q *Queries) DeletePomodoroProfile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePomodoroProfile, id)
	return err
}

const findLatestOpenWorkSession = `-- name: FindLatestOpenWorkSession :one
SELECT id FROM pomodoro_sessions
WHERE session_type = 'work'
  AND ended_at IS NULL
  AND deleted_at IS NULL
ORDER BY started_at DESC, id DESC
LIMIT 1
`

func (q *Queries) FindLatestOpenWorkSession(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, findLatestOpenWorkSession)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPomodoroConfig = `-- name: GetPomodoroConfig :one
SELECT id, work_seconds, short_break_seconds, long_break_seconds, sessions_before_long_break, auto_start_next_phase FROM pomodoro_config
WHERE id = 1
`

func (q *Queries) GetPomodoroConfig(ctx context.Context) (PomodoroConfig, error) {
	row := q.db.QueryRow(ctx, getPomodoroConfig)
	var i PomodoroConfig
	err := row.Scan(
		&i.ID,
		&i.WorkSeconds,
		&i.ShortBreakSeconds,
		&i.LongBreakSeconds,
		&i.SessionsBeforeLongBreak,
		&i.AutoStartNextPhase,
	)
	return i, err
}

const getPomodoroProfile = `-- name: GetPomodoroProfile :one
SELECT id, name, work_seconds, short_break_seconds, long_break_seconds, sessions_before_long_break, is_builtin, created_at, updated_at FROM pomodoro_profiles
WHERE id = $1
`

func (q *Queries) GetPomodoroProfile(ctx context.Context, id int64) (PomodoroProfile, error) {
	row := q.db.QueryRow(ctx, getPomodoroProfile, id)
	var i PomodoroProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkSeconds,
		&i.ShortBreakSeconds,
		&i.LongBreakSeconds,
		&i.SessionsBeforeLongBreak,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPomodoroSession = `-- name: GetPomodoroSession :one
SELECT id, sync_id, started_at, ended_at, session_type, task_id, deleted_at FROM pomodoro_sessions
WHERE id = $1
`

func (q *Queries) GetPomodoroSession(ctx context.Context, id int64) (PomodoroSession, error) {
	row := q.db.QueryRow(ctx, getPomodoroSession, id)
	var i PomodoroSession
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.StartedAt,
		&i.EndedAt,
		&i.SessionType,
		&i.TaskID,
		&i.DeletedAt,
	)
	return i, err
}

const getRuntimeState = `-- name: GetRuntimeState :one
SELECT id, phase, remaining_seconds, total_seconds, is_running, active_session_id, date_key, last_seen_at, interrupted, created_at, updated_at FROM pomodoro_runtime_state
WHERE id = 1
`

func (q *Queries) GetRuntimeState(ctx context.Context) (PomodoroRuntimeState, error) {
	row := q.db.QueryRow(ctx, getRuntimeState)
	var i PomodoroRuntimeState
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.RemainingSeconds,
		&i.TotalSeconds,
		&i.IsRunning,
		&i.ActiveSessionID,
		&i.DateKey,
		&i.LastSeenAt,
		&i.Interrupted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPomodoroSessionsForSync = `-- name: ListAllPomodoroSessionsForSync :many
SELECT id, sync_id, started_at, ended_at, session_type, task_id, deleted_at FROM pomodoro_sessions
ORDER BY id ASC
`

func (q *Queries) ListAllPomodoroSessionsForSync(ctx context.Context) ([]PomodoroSession, error) {
	rows, err := q.db.Query(ctx, listAllPomodoroSessionsForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PomodoroSession{}
	for rows.Next() {
		var i PomodoroSession
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.StartedAt,
			&i.EndedAt,
			&i.SessionType,
			&i.TaskID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPomodoroProfiles = `-- name: ListPomodoroProfiles :many
SELECT id, name, work_seconds, short_break_seconds, long_break_seconds, sessions_before_long_break, is_builtin, created_at, updated_at FROM pomodoro_profiles
ORDER BY is_builtin DESC, name ASC
`

func (q *Queries) ListPomodoroProfiles(ctx context.Context) ([]PomodoroProfile, error) {
	rows, err := q.db.Query(ctx, listPomodoroProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PomodoroProfile{}
	for rows.Next() {
		var i PomodoroProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkSeconds,
			&i.ShortBreakSeconds,
			&i.LongBreakSeconds,
			&i.SessionsBeforeLongBreak,
			&i.IsBuiltin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPomodoroSessions = `-- name: ListPomodoroSessions :many
SELECT id, sync_id, started_at, ended_at, session_type, task_id, deleted_at FROM pomodoro_sessions
WHERE deleted_at IS NULL
ORDER BY started_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListPomodoroSessionsParams struct {
	OffsetValue int32
	LimitValue  int32
}

func (q *Queries) ListPomodoroSessions(ctx context.Context, arg ListPomodoroSessionsParams) ([]PomodoroSession, error) {
	rows, err := q.db.Query(ctx, listPomodoroSessions, arg.OffsetValue, arg.LimitValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PomodoroSession{}
	for rows.Next() {
		var i PomodoroSession
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.StartedAt,
			&i.EndedAt,
			&i.SessionType,
			&i.TaskID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPomodoroSessionsByTask = `-- name: ListPomodoroSessionsByTask :many
SELECT id, sync_id, started_at, ended_at, session_type, task_id, deleted_at FROM pomodoro_sessions
WHERE task_id = $1 AND deleted_at IS NULL
ORDER BY started_at DESC, id DESC
`

func (q *Queries) ListPomodoroSessionsByTask(ctx context.Context, taskID pgtype.Int8) ([]PomodoroSession, error) {
	rows, err := q.db.Query(ctx, listPomodoroSessionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PomodoroSession{}
	for rows.Next() {
		var i PomodoroSession
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.StartedAt,
			&i.EndedAt,
			&i.SessionType,
			&i.TaskID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPomodoroSessionTask = `-- name: SetPomodoroSessionTask :exec
UPDATE pomodoro_sessions
SET task_id = $1
WHERE id = $2
  AND task_id IS NULL
`

type SetPomodoroSessionTaskParams struct {
	TaskID pgtype.Int8
	ID     int64
}

func (q *Queries) SetPomodoroSessionTask(ctx context.Context, arg SetPomodoroSessionTaskParams) error {
	_, err := q.db.Exec(ctx, setPomodoroSessionTask, arg.TaskID, arg.ID)
	return err
}

const softDeletePomodoroSession = `-- name: SoftDeletePomodoroSession :exec
UPDATE pomodoro_sessions
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeletePomodoroSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeletePomodoroSession, id)
	return err
}

const updatePomodoroConfig = `-- name: UpdatePomodoroConfig :exec
UPDATE pomodoro_config
SET work_seconds = $1,
    short_break_seconds = $2,
    long_break_seconds = $3,
    sessions_before_long_break = $4,
    auto_start_next_phase = $5
WHERE id = 1
`

type UpdatePomodoroConfigParams struct {
	WorkSeconds             int32
	ShortBreakSeconds       int32
	LongBreakSeconds        int32
	SessionsBeforeLongBreak int32
	AutoStartNextPhase      bool
}

func (q *Queries) UpdatePomodoroConfig(ctx context.Context, arg UpdatePomodoroConfigParams) error {
	_, err := q.db.Exec(ctx, updatePomodoroConfig,
		arg.WorkSeconds,
		arg.ShortBreakSeconds,
		arg.LongBreakSeconds,
		arg.SessionsBeforeLongBreak,
		arg.AutoStartNextPhase,
	)
	return err
}

const updatePomodoroProfile = `-- name: UpdatePomodoroProfile :exec
UPDATE pomodoro_profiles
SET name = $1,
    work_seconds = $2,
    short_break_seconds = $3,
    long_break_seconds = $4,
    sessions_before_long_break = $5,
    updated_at = now()
WHERE id = $6 AND is_builtin = false
`

type UpdatePomodoroProfileParams struct {
	Name                    string
	WorkSeconds             int32
	ShortBreakSeconds       int32
	LongBreakSeconds        int32
	SessionsBeforeLongBreak int32
	ID                      int64
}

func (q *Queries) UpdatePomodoroProfile(ctx context.Context, arg UpdatePomodoroProfileParams) error {
	_, err := q.db.Exec(ctx, updatePomodoroProfile,
		arg.Name,
		arg.WorkSeconds,
		arg.ShortBreakSeconds,
		arg.LongBreakSeconds,
		arg.SessionsBeforeLongBreak,
		arg.ID,
	)
	return err
}

const updatePomodoroSessionEnd = `-- name: UpdatePomodoroSessionEnd :exec
UPDATE pomodoro_sessions
SET ended_at = $1
WHERE id = $2
`

type UpdatePomodoroSessionEndParams struct {
	EndedAt pgtype.Timestamptz
	ID      int64
}

func (q *Queries) UpdatePomodoroSessionEnd(ctx context.Context, arg UpdatePomodoroSessionEndParams) error {
	_, err := q.db.Exec(ctx, updatePomodoroSessionEnd, arg.EndedAt, arg.ID)
	return err
}

const updateRuntimeState = `-- name: UpdateRuntimeState :exec
UPDATE pomodoro_runtime_state
SET phase = $1,
    remaining_seconds = $2,
    total_seconds = $3,
    is_running = $4,
    active_session_id = $5,
    date_key = $6,
    last_seen_at = now(),
    interrupted = $7,
    updated_at = now()
WHERE id = 1
`

type UpdateRuntimeStateParams struct {
	Phase            string
	RemainingSeconds int32
	TotalSeconds     int32
	IsRunning        bool
	ActiveSessionID  pgtype.Int8
	DateKey          pgtype.Date
	Interrupted      bool
}

func (q *Queries) UpdateRuntimeState(ctx context.Context, arg UpdateRuntimeStateParams) error {
	_, err := q.db.Exec(ctx, updateRuntimeState,
		arg.Phase,
		arg.RemainingSeconds,
		arg.TotalSeconds,
		arg.IsRunning,
		arg.ActiveSessionID,
		arg.DateKey,
		arg.Interrupted,
	)
	return err
}
