// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: semester.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTermPhase = `-- name: CreateTermPhase :one
INSERT INTO term_phases (
    sync_id,
    term_label,
    phase_type,
    start_week,
    end_week,
    affects_courses,
    affects_exam_notifications,
    pomodoro_profile,
    notification_rules,
    sort_order
) VALUES (
    COALESCE(NULLIF($1::text, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at
`

type CreateTermPhaseParams struct {
	SyncID                   string
	TermLabel                string
	PhaseType                string
	StartWeek                int32
	EndWeek                  int32
	AffectsCourses           bool
	AffectsExamNotifications bool
	PomodoroProfile          string
	NotificationRules        []byte
	SortOrder                int32
}

func (q *Queries) CreateTermPhase(ctx context.Context, arg CreateTermPhaseParams) (TermPhase, error) {
	row := q.db.QueryRow(ctx, createTermPhase,
		arg.SyncID,
		arg.TermLabel,
		arg.PhaseType,
		arg.StartWeek,
		arg.EndWeek,
		arg.AffectsCourses,
		arg.AffectsExamNotifications,
		arg.PomodoroProfile,
		arg.NotificationRules,
		arg.SortOrder,
	)
	var i TermPhase
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.TermLabel,
		&i.PhaseType,
		&i.StartWeek,
		&i.EndWeek,
		&i.AffectsCourses,
		&i.AffectsExamNotifications,
		&i.PomodoroProfile,
		&i.NotificationRules,
		&i.SortOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSemesterContextBySource = `-- name: GetLatestSemesterContextBySource :one
SELECT id, source, academic_year, term, term_label, start_date, current_week, total_weeks, refreshed_at, created_at, updated_at FROM semester_context
WHERE source = $1
ORDER BY refreshed_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestSemesterContextBySource(ctx context.Context, source string) (SemesterContext, error) {
	row := q.db.QueryRow(ctx, getLatestSemesterContextBySource, source)
	var i SemesterContext
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.AcademicYear,
		&i.Term,
		&i.TermLabel,
		&i.StartDate,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSemesterContext = `-- name: GetSemesterContext :one
SELECT id, source, academic_year, term, term_label, start_date, current_week, total_weeks, refreshed_at, created_at, updated_at FROM semester_context
WHERE source = $1 AND term_label = $2
`

type GetSemesterContextParams struct {
	Source    string
	TermLabel string
}

func (q *Queries) GetSemesterContext(ctx context.Context, arg GetSemesterContextParams) (SemesterContext, error) {
	row := q.db.QueryRow(ctx, getSemesterContext, arg.Source, arg.TermLabel)
	var i SemesterContext
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.AcademicYear,
		&i.Term,
		&i.TermLabel,
		&i.StartDate,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTermPhase = `-- name: GetTermPhase :one
SELECT id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at FROM term_phases
WHERE id = $1
`

func (q *Queries) GetTermPhase(ctx context.Context, id int64) (TermPhase, error) {
	row := q.db.QueryRow(ctx, getTermPhase, id)
	var i TermPhase
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.TermLabel,
		&i.PhaseType,
		&i.StartWeek,
		&i.EndWeek,
		&i.AffectsCourses,
		&i.AffectsExamNotifications,
		&i.PomodoroProfile,
		&i.NotificationRules,
		&i.SortOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTermPhaseByWeek = `-- name: GetTermPhaseByWeek :one
SELECT id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at FROM term_phases
WHERE term_label = $1
  AND deleted_at IS NULL
  AND start_week <= $2
  AND end_week >= $2
ORDER BY sort_order ASC, start_week DESC, id DESC
LIMIT 1
`

type GetTermPhaseByWeekParams struct {
	TermLabel string
	WeekIndex int32
}

func (q *Queries) GetTermPhaseByWeek(ctx context.Context, arg GetTermPhaseByWeekParams) (TermPhase, error) {
	row := q.db.QueryRow(ctx, getTermPhaseByWeek, arg.TermLabel, arg.WeekIndex)
	var i TermPhase
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.TermLabel,
		&i.PhaseType,
		&i.StartWeek,
		&i.EndWeek,
		&i.AffectsCourses,
		&i.AffectsExamNotifications,
		&i.PomodoroProfile,
		&i.NotificationRules,
		&i.SortOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTermPhases = `-- name: ListAllTermPhases :many
SELECT id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at FROM term_phases
ORDER BY id ASC
`

func (q *Queries) ListAllTermPhases(ctx context.Context) ([]TermPhase, error) {
	rows, err := q.db.Query(ctx, listAllTermPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TermPhase{}
	for rows.Next() {
		var i TermPhase
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.TermLabel,
			&i.PhaseType,
			&i.StartWeek,
			&i.EndWeek,
			&i.AffectsCourses,
			&i.AffectsExamNotifications,
			&i.PomodoroProfile,
			&i.NotificationRules,
			&i.SortOrder,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemesterContexts = `-- name: ListSemesterContexts :many
SELECT id, source, academic_year, term, term_label, start_date, current_week, total_weeks, refreshed_at, created_at, updated_at FROM semester_context
ORDER BY source ASC, term_label ASC
`

func (q *Queries) ListSemesterContexts(ctx context.Context) ([]SemesterContext, error) {
	rows, err := q.db.Query(ctx, listSemesterContexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SemesterContext{}
	for rows.Next() {
		var i SemesterContext
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.AcademicYear,
			&i.Term,
			&i.TermLabel,
			&i.StartDate,
			&i.CurrentWeek,
			&i.TotalWeeks,
			&i.RefreshedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTermPhases = `-- name: ListTermPhases :many
SELECT id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at FROM term_phases
WHERE term_label = $1 AND deleted_at IS NULL
ORDER BY sort_order ASC, start_week ASC, id ASC
`

func (q *Queries) ListTermPhases(ctx context.Context, termLabel string) ([]TermPhase, error) {
	rows, err := q.db.Query(ctx, listTermPhases, termLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TermPhase{}
	for rows.Next() {
		var i TermPhase
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.TermLabel,
			&i.PhaseType,
			&i.StartWeek,
			&i.EndWeek,
			&i.AffectsCourses,
			&i.AffectsExamNotifications,
			&i.PomodoroProfile,
			&i.NotificationRules,
			&i.SortOrder,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTermPhase = `-- name: SoftDeleteTermPhase :exec
UPDATE term_phases
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTermPhase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteTermPhase, id)
	return err
}

const updateAllSemesterContextsStartDate = `-- name: UpdateAllSemesterContextsStartDate :execrows
UPDATE semester_context
SET start_date = $1, updated_at = now()
`

func (q *Queries) UpdateAllSemesterContextsStartDate(ctx context.Context, startDate pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, updateAllSemesterContextsStartDate, startDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTermPhase = `-- name: UpdateTermPhase :one
UPDATE term_phases
SET term_label = $1,
    phase_type = $2,
    start_week = $3,
    end_week = $4,
    affects_courses = $5,
    affects_exam_notifications = $6,
    pomodoro_profile = $7,
    notification_rules = $8,
    sort_order = $9,
    updated_at = now()
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, sync_id, term_label, phase_type, start_week, end_week, affects_courses, affects_exam_notifications, pomodoro_profile, notification_rules, sort_order, deleted_at, created_at, updated_at
`

type UpdateTermPhaseParams struct {
	TermLabel                string
	PhaseType                string
	StartWeek                int32
	EndWeek                  int32
	AffectsCourses           bool
	AffectsExamNotifications bool
	PomodoroProfile          string
	NotificationRules        []byte
	SortOrder                int32
	ID                       int64
}

func (q *Queries) UpdateTermPhase(ctx context.Context, arg UpdateTermPhaseParams) (TermPhase, error) {
	row := q.db.QueryRow(ctx, updateTermPhase,
		arg.TermLabel,
		arg.PhaseType,
		arg.StartWeek,
		arg.EndWeek,
		arg.AffectsCourses,
		arg.AffectsExamNotifications,
		arg.PomodoroProfile,
		arg.NotificationRules,
		arg.SortOrder,
		arg.ID,
	)
	var i TermPhase
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.TermLabel,
		&i.PhaseType,
		&i.StartWeek,
		&i.EndWeek,
		&i.AffectsCourses,
		&i.AffectsExamNotifications,
		&i.PomodoroProfile,
		&i.NotificationRules,
		&i.SortOrder,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSemesterContext = `-- name: UpsertSemesterContext :one
INSERT INTO semester_context (
    source,
    academic_year,
    term,
    term_label,
    start_date,
    current_week,
    total_weeks,
    refreshed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    now()
)
ON CONFLICT (source, term_label) DO UPDATE SET
    academic_year = EXCLUDED.academic_year,
    term = EXCLUDED.term,
    start_date = EXCLUDED.start_date,
    current_week = EXCLUDED.current_week,
    total_weeks = EXCLUDED.total_weeks,
    refreshed_at = EXCLUDED.refreshed_at,
    updated_at = now()
RETURNING id, source, academic_year, term, term_label, start_date, current_week, total_weeks, refreshed_at, created_at, updated_at
`

type UpsertSemesterContextParams struct {
	Source       string
	AcademicYear pgtype.Text
	Term         pgtype.Text
	TermLabel    string
	StartDate    pgtype.Date
	CurrentWeek  pgtype.Int4
	TotalWeeks   pgtype.Int4
}

func (q *Queries) UpsertSemesterContext(ctx context.Context, arg UpsertSemesterContextParams) (SemesterContext, error) {
	row := q.db.QueryRow(ctx, upsertSemesterContext,
		arg.Source,
		arg.AcademicYear,
		arg.Term,
		arg.TermLabel,
		arg.StartDate,
		arg.CurrentWeek,
		arg.TotalWeeks,
	)
	var i SemesterContext
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.AcademicYear,
		&i.Term,
		&i.TermLabel,
		&i.StartDate,
		&i.CurrentWeek,
		&i.TotalWeeks,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
