// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSyncDeviceIds = `-- name: EnsureSyncDeviceIds :execrows
UPDATE sync_config
SET device_id = CASE WHEN device_id IS NULL OR device_id = '' THEN $1 ELSE device_id END,
    dataset_id = CASE WHEN dataset_id IS NULL OR dataset_id = '' THEN $2 ELSE dataset_id END
WHERE id = 1
`

type EnsureSyncDeviceIdsParams struct {
	DeviceID  pgtype.Text
	DatasetID pgtype.Text
}

func (q *Queries) EnsureSyncDeviceIds(ctx context.Context, arg EnsureSyncDeviceIdsParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureSyncDeviceIds, arg.DeviceID, arg.DatasetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSyncConfig = `-- name: GetSyncConfig :one
SELECT id, server_url, username, password, auto_sync, last_sync_at, remote_etag, device_id, dataset_id, ai_settings_remote_etag FROM sync_config
WHERE id = 1
`

func (q *Queries) GetSyncConfig(ctx context.Context) (SyncConfig, error) {
	row := q.db.QueryRow(ctx, getSyncConfig)
	var i SyncConfig
	err := row.Scan(
		&i.ID,
		&i.ServerUrl,
		&i.Username,
		&i.Password,
		&i.AutoSync,
		&i.LastSyncAt,
		&i.RemoteEtag,
		&i.DeviceID,
		&i.DatasetID,
		&i.AiSettingsRemoteEtag,
	)
	return i, err
}

const syncFindCourseIDBySyncID = `-- name: SyncFindCourseIDBySyncID :one
SELECT id FROM courses WHERE sync_id = $1
`

func (q *Queries) SyncFindCourseIDBySyncID(ctx context.Context, syncID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, syncFindCourseIDBySyncID, syncID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const syncFindCourseMeta = `-- name: SyncFindCourseMeta :one
SELECT id, sync_id, updated_at, deleted_at
FROM courses
WHERE sync_id = $1
`

type SyncFindCourseMetaRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindCourseMeta(ctx context.Context, syncID pgtype.Text) (SyncFindCourseMetaRow, error) {
	row := q.db.QueryRow(ctx, syncFindCourseMeta, syncID)
	var i SyncFindCourseMetaRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindCourseMetaByID = `-- name: SyncFindCourseMetaByID :one
SELECT id, sync_id, updated_at, deleted_at
FROM courses
WHERE id = $1
`

type SyncFindCourseMetaByIDRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindCourseMetaByID(ctx context.Context, id int64) (SyncFindCourseMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, syncFindCourseMetaByID, id)
	var i SyncFindCourseMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindExamMeta = `-- name: SyncFindExamMeta :one
SELECT id, sync_id, updated_at, deleted_at
FROM exams
WHERE sync_id = $1
`

type SyncFindExamMetaRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindExamMeta(ctx context.Context, syncID pgtype.Text) (SyncFindExamMetaRow, error) {
	row := q.db.QueryRow(ctx, syncFindExamMeta, syncID)
	var i SyncFindExamMetaRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindExamMetaByID = `-- name: SyncFindExamMetaByID :one
SELECT id, sync_id, updated_at, deleted_at
FROM exams
WHERE id = $1
`

type SyncFindExamMetaByIDRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindExamMetaByID(ctx context.Context, id int64) (SyncFindExamMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, syncFindExamMetaByID, id)
	var i SyncFindExamMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindSessionMeta = `-- name: SyncFindSessionMeta :one
SELECT id, sync_id, ended_at, deleted_at
FROM pomodoro_sessions
WHERE sync_id = $1
`

type SyncFindSessionMetaRow struct {
	ID        int64
	SyncID    pgtype.Text
	EndedAt   pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindSessionMeta(ctx context.Context, syncID pgtype.Text) (SyncFindSessionMetaRow, error) {
	row := q.db.QueryRow(ctx, syncFindSessionMeta, syncID)
	var i SyncFindSessionMetaRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.EndedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindSessionMetaByID = `-- name: SyncFindSessionMetaByID :one
SELECT id, sync_id, ended_at, deleted_at
FROM pomodoro_sessions
WHERE id = $1
`

type SyncFindSessionMetaByIDRow struct {
	ID        int64
	SyncID    pgtype.Text
	EndedAt   pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindSessionMetaByID(ctx context.Context, id int64) (SyncFindSessionMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, syncFindSessionMetaByID, id)
	var i SyncFindSessionMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.EndedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindTaskIDBySyncID = `-- name: SyncFindTaskIDBySyncID :one
SELECT id FROM tasks WHERE sync_id = $1
`

func (q *Queries) SyncFindTaskIDBySyncID(ctx context.Context, syncID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, syncFindTaskIDBySyncID, syncID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const syncFindTaskMeta = `-- name: SyncFindTaskMeta :one

SELECT id, sync_id, updated_at, deleted_at
FROM tasks
WHERE sync_id = $1
`

type SyncFindTaskMetaRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

// ── v2 snapshot merge queries (port of src-tauri/src/sync/exporter.rs) ──────
func (q *Queries) SyncFindTaskMeta(ctx context.Context, syncID pgtype.Text) (SyncFindTaskMetaRow, error) {
	row := q.db.QueryRow(ctx, syncFindTaskMeta, syncID)
	var i SyncFindTaskMetaRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindTaskMetaByID = `-- name: SyncFindTaskMetaByID :one
SELECT id, sync_id, updated_at, deleted_at
FROM tasks
WHERE id = $1
`

type SyncFindTaskMetaByIDRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindTaskMetaByID(ctx context.Context, id int64) (SyncFindTaskMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, syncFindTaskMetaByID, id)
	var i SyncFindTaskMetaByIDRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncFindTermPhaseMeta = `-- name: SyncFindTermPhaseMeta :one
SELECT id, sync_id, updated_at, deleted_at
FROM term_phases
WHERE sync_id = $1
`

type SyncFindTermPhaseMetaRow struct {
	ID        int64
	SyncID    pgtype.Text
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) SyncFindTermPhaseMeta(ctx context.Context, syncID pgtype.Text) (SyncFindTermPhaseMetaRow, error) {
	row := q.db.QueryRow(ctx, syncFindTermPhaseMeta, syncID)
	var i SyncFindTermPhaseMetaRow
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const syncGetTaskDailyFields = `-- name: SyncGetTaskDailyFields :one
SELECT is_daily, last_completed_date, reminder_time
FROM tasks
WHERE id = $1
`

type SyncGetTaskDailyFieldsRow struct {
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
}

func (q *Queries) SyncGetTaskDailyFields(ctx context.Context, id int64) (SyncGetTaskDailyFieldsRow, error) {
	row := q.db.QueryRow(ctx, syncGetTaskDailyFields, id)
	var i SyncGetTaskDailyFieldsRow
	err := row.Scan(&i.IsDaily, &i.LastCompletedDate, &i.ReminderTime)
	return i, err
}

const syncInsertCourse = `-- name: SyncInsertCourse :exec
INSERT INTO courses (
    sync_id, name, day_of_week, start_time, end_time, week_pattern, semester_start_date,
    location, teacher, color, semester, created_at, updated_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
`

type SyncInsertCourseParams struct {
	SyncID            pgtype.Text
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	WeekPattern       string
	SemesterStartDate pgtype.Date
	Location          string
	Teacher           string
	Color             string
	Semester          string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

func (q *Queries) SyncInsertCourse(ctx context.Context, arg SyncInsertCourseParams) error {
	_, err := q.db.Exec(ctx, syncInsertCourse,
		arg.SyncID,
		arg.Name,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.SemesterStartDate,
		arg.Location,
		arg.Teacher,
		arg.Color,
		arg.Semester,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const syncInsertExam = `-- name: SyncInsertExam :exec
INSERT INTO exams (
    sync_id, course_name, exam_datetime, exam_end_datetime, location, notes, course_id, semester,
    created_at, updated_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11
)
`

type SyncInsertExamParams struct {
	SyncID          pgtype.Text
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
	Notes           string
	CourseID        pgtype.Int8
	Semester        string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

func (q *Queries) SyncInsertExam(ctx context.Context, arg SyncInsertExamParams) error {
	_, err := q.db.Exec(ctx, syncInsertExam,
		arg.SyncID,
		arg.CourseName,
		arg.ExamDatetime,
		arg.ExamEndDatetime,
		arg.Location,
		arg.Notes,
		arg.CourseID,
		arg.Semester,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const syncInsertSession = `-- name: SyncInsertSession :exec
INSERT INTO pomodoro_sessions (sync_id, started_at, ended_at, session_type, task_id, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SyncInsertSessionParams struct {
	SyncID      pgtype.Text
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	SessionType string
	TaskID      pgtype.Int8
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) SyncInsertSession(ctx context.Context, arg SyncInsertSessionParams) error {
	_, err := q.db.Exec(ctx, syncInsertSession,
		arg.SyncID,
		arg.StartedAt,
		arg.EndedAt,
		arg.SessionType,
		arg.TaskID,
		arg.DeletedAt,
	)
	return err
}

const syncInsertTask = `-- name: SyncInsertTask :exec
INSERT INTO tasks (
    sync_id, title, description, status, priority, due_date, tags,
    created_at, updated_at, is_daily, last_completed_date, reminder_time, remind_at, deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14
)
`

type SyncInsertTaskParams struct {
	SyncID            pgtype.Text
	Title             string
	Description       string
	Status            string
	Priority          string
	DueDate           pgtype.Date
	Tags              []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
	RemindAt          pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

func (q *Queries) SyncInsertTask(ctx context.Context, arg SyncInsertTaskParams) error {
	_, err := q.db.Exec(ctx, syncInsertTask,
		arg.SyncID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDaily,
		arg.LastCompletedDate,
		arg.ReminderTime,
		arg.RemindAt,
		arg.DeletedAt,
	)
	return err
}

const syncInsertTermPhase = `-- name: SyncInsertTermPhase :exec
INSERT INTO term_phases (
    sync_id, term_label, phase_type, start_week, end_week, affects_courses,
    affects_exam_notifications, pomodoro_profile, notification_rules, sort_order,
    deleted_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
`

type SyncInsertTermPhaseParams struct {
	SyncID                   pgtype.Text
	TermLabel                string
	PhaseType                string
	StartWeek                int32
	EndWeek                  int32
	AffectsCourses           bool
	AffectsExamNotifications bool
	PomodoroProfile          string
	NotificationRules        []byte
	SortOrder                int32
	DeletedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

func (q *Queries) SyncInsertTermPhase(ctx context.Context, arg SyncInsertTermPhaseParams) error {
	_, err := q.db.Exec(ctx, syncInsertTermPhase,
		arg.SyncID,
		arg.TermLabel,
		arg.PhaseType,
		arg.StartWeek,
		arg.EndWeek,
		arg.AffectsCourses,
		arg.AffectsExamNotifications,
		arg.PomodoroProfile,
		arg.NotificationRules,
		arg.SortOrder,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const syncUpdateCourse = `-- name: SyncUpdateCourse :exec
UPDATE courses
SET name = $1,
    day_of_week = $2,
    start_time = $3,
    end_time = $4,
    week_pattern = $5,
    semester_start_date = $6,
    location = $7,
    teacher = $8,
    color = $9,
    semester = $10,
    created_at = $11,
    updated_at = $12,
    deleted_at = $13,
    sync_id = $14
WHERE id = $15
`

type SyncUpdateCourseParams struct {
	Name              string
	DayOfWeek         int32
	StartTime         pgtype.Time
	EndTime           pgtype.Time
	WeekPattern       string
	SemesterStartDate pgtype.Date
	Location          string
	Teacher           string
	Color             string
	Semester          string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	SyncID            pgtype.Text
	ID                int64
}

func (q *Queries) SyncUpdateCourse(ctx context.Context, arg SyncUpdateCourseParams) error {
	_, err := q.db.Exec(ctx, syncUpdateCourse,
		arg.Name,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.WeekPattern,
		arg.SemesterStartDate,
		arg.Location,
		arg.Teacher,
		arg.Color,
		arg.Semester,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.SyncID,
		arg.ID,
	)
	return err
}

const syncUpdateCourseSyncID = `-- name: SyncUpdateCourseSyncID :exec
UPDATE courses
SET sync_id = $1
WHERE id = $2
`

type SyncUpdateCourseSyncIDParams struct {
	SyncID pgtype.Text
	ID     int64
}

func (q *Queries) SyncUpdateCourseSyncID(ctx context.Context, arg SyncUpdateCourseSyncIDParams) error {
	_, err := q.db.Exec(ctx, syncUpdateCourseSyncID, arg.SyncID, arg.ID)
	return err
}

const syncUpdateExam = `-- name: SyncUpdateExam :exec
UPDATE exams
SET course_name = $1,
    exam_datetime = $2,
    exam_end_datetime = $3,
    location = $4,
    notes = $5,
    course_id = $6,
    semester = $7,
    created_at = $8,
    updated_at = $9,
    deleted_at = $10,
    sync_id = $11
WHERE id = $12
`

type SyncUpdateExamParams struct {
	CourseName      string
	ExamDatetime    pgtype.Timestamptz
	ExamEndDatetime pgtype.Timestamptz
	Location        string
	Notes           string
	CourseID        pgtype.Int8
	Semester        string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	SyncID          pgtype.Text
	ID              int64
}

func (q *Queries) SyncUpdateExam(ctx context.Context, arg SyncUpdateExamParams) error {
	_, err := q.db.Exec(ctx, syncUpdateExam,
		arg.CourseName,
		arg.ExamDatetime,
		arg.ExamEndDatetime,
		arg.Location,
		arg.Notes,
		arg.CourseID,
		arg.Semester,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.SyncID,
		arg.ID,
	)
	return err
}

const syncUpdateExamSyncID = `-- name: SyncUpdateExamSyncID :exec
UPDATE exams
SET sync_id = $1
WHERE id = $2
`

type SyncUpdateExamSyncIDParams struct {
	SyncID pgtype.Text
	ID     int64
}

func (q *Queries) SyncUpdateExamSyncID(ctx context.Context, arg SyncUpdateExamSyncIDParams) error {
	_, err := q.db.Exec(ctx, syncUpdateExamSyncID, arg.SyncID, arg.ID)
	return err
}

const syncUpdateSession = `-- name: SyncUpdateSession :exec
UPDATE pomodoro_sessions
SET started_at = $1,
    ended_at = $2,
    session_type = $3,
    task_id = $4,
    deleted_at = $5,
    sync_id = $6
WHERE id = $7
`

type SyncUpdateSessionParams struct {
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	SessionType string
	TaskID      pgtype.Int8
	DeletedAt   pgtype.Timestamptz
	SyncID      pgtype.Text
	ID          int64
}

func (q *Queries) SyncUpdateSession(ctx context.Context, arg SyncUpdateSessionParams) error {
	_, err := q.db.Exec(ctx, syncUpdateSession,
		arg.StartedAt,
		arg.EndedAt,
		arg.SessionType,
		arg.TaskID,
		arg.DeletedAt,
		arg.SyncID,
		arg.ID,
	)
	return err
}

const syncUpdateSessionSyncID = `-- name: SyncUpdateSessionSyncID :exec
UPDATE pomodoro_sessions
SET sync_id = $1
WHERE id = $2
`

type SyncUpdateSessionSyncIDParams struct {
	SyncID pgtype.Text
	ID     int64
}

func (q *Queries) SyncUpdateSessionSyncID(ctx context.Context, arg SyncUpdateSessionSyncIDParams) error {
	_, err := q.db.Exec(ctx, syncUpdateSessionSyncID, arg.SyncID, arg.ID)
	return err
}

const syncUpdateTask = `-- name: SyncUpdateTask :exec
UPDATE tasks
SET title = $1,
    description = $2,
    status = $3,
    priority = $4,
    due_date = $5,
    tags = $6,
    created_at = $7,
    updated_at = $8,
    is_daily = $9,
    last_completed_date = $10,
    reminder_time = $11,
    remind_at = $12,
    deleted_at = $13,
    sync_id = $14
WHERE id = $15
`

type SyncUpdateTaskParams struct {
	Title             string
	Description       string
	Status            string
	Priority          string
	DueDate           pgtype.Date
	Tags              []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
	RemindAt          pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	SyncID            pgtype.Text
	ID                int64
}

func (q *Queries) SyncUpdateTask(ctx context.Context, arg SyncUpdateTaskParams) error {
	_, err := q.db.Exec(ctx, syncUpdateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsDaily,
		arg.LastCompletedDate,
		arg.ReminderTime,
		arg.RemindAt,
		arg.DeletedAt,
		arg.SyncID,
		arg.ID,
	)
	return err
}

const syncUpdateTaskDailyFields = `-- name: SyncUpdateTaskDailyFields :exec
UPDATE tasks
SET is_daily = $1,
    last_completed_date = $2,
    reminder_time = $3
WHERE id = $4
`

type SyncUpdateTaskDailyFieldsParams struct {
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
	ID                int64
}

func (q *Queries) SyncUpdateTaskDailyFields(ctx context.Context, arg SyncUpdateTaskDailyFieldsParams) error {
	_, err := q.db.Exec(ctx, syncUpdateTaskDailyFields,
		arg.IsDaily,
		arg.LastCompletedDate,
		arg.ReminderTime,
		arg.ID,
	)
	return err
}

const syncUpdateTaskSyncID = `-- name: SyncUpdateTaskSyncID :exec
UPDATE tasks
SET sync_id = $1
WHERE id = $2
`

type SyncUpdateTaskSyncIDParams struct {
	SyncID pgtype.Text
	ID     int64
}

func (q *Queries) SyncUpdateTaskSyncID(ctx context.Context, arg SyncUpdateTaskSyncIDParams) error {
	_, err := q.db.Exec(ctx, syncUpdateTaskSyncID, arg.SyncID, arg.ID)
	return err
}

const syncUpdateTermPhase = `-- name: SyncUpdateTermPhase :exec
UPDATE term_phases
SET term_label = $1,
    phase_type = $2,
    start_week = $3,
    end_week = $4,
    affects_courses = $5,
    affects_exam_notifications = $6,
    pomodoro_profile = $7,
    notification_rules = $8,
    sort_order = $9,
    deleted_at = $10,
    created_at = $11,
    updated_at = $12
WHERE id = $13
`

type SyncUpdateTermPhaseParams struct {
	TermLabel                string
	PhaseType                string
	StartWeek                int32
	EndWeek                  int32
	AffectsCourses           bool
	AffectsExamNotifications bool
	PomodoroProfile          string
	NotificationRules        []byte
	SortOrder                int32
	DeletedAt                pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	ID                       int64
}

func (q *Queries) SyncUpdateTermPhase(ctx context.Context, arg SyncUpdateTermPhaseParams) error {
	_, err := q.db.Exec(ctx, syncUpdateTermPhase,
		arg.TermLabel,
		arg.PhaseType,
		arg.StartWeek,
		arg.EndWeek,
		arg.AffectsCourses,
		arg.AffectsExamNotifications,
		arg.PomodoroProfile,
		arg.NotificationRules,
		arg.SortOrder,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSyncAiSettingsRemoteEtag = `-- name: UpdateSyncAiSettingsRemoteEtag :exec
UPDATE sync_config
SET ai_settings_remote_etag = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncAiSettingsRemoteEtag(ctx context.Context, aiSettingsRemoteEtag pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateSyncAiSettingsRemoteEtag, aiSettingsRemoteEtag)
	return err
}

const updateSyncConfigCredentials = `-- name: UpdateSyncConfigCredentials :exec
UPDATE sync_config
SET server_url = $1,
    username = $2,
    password = $3,
    auto_sync = $4
WHERE id = 1
`

type UpdateSyncConfigCredentialsParams struct {
	ServerUrl string
	Username  string
	Password  string
	AutoSync  bool
}

func (q *Queries) UpdateSyncConfigCredentials(ctx context.Context, arg UpdateSyncConfigCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateSyncConfigCredentials,
		arg.ServerUrl,
		arg.Username,
		arg.Password,
		arg.AutoSync,
	)
	return err
}

const updateSyncLastSyncAt = `-- name: UpdateSyncLastSyncAt :exec
UPDATE sync_config
SET last_sync_at = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncLastSyncAt(ctx context.Context, lastSyncAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateSyncLastSyncAt, lastSyncAt)
	return err
}

const updateSyncRemoteEtag = `-- name: UpdateSyncRemoteEtag :exec
UPDATE sync_config
SET remote_etag = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncRemoteEtag(ctx context.Context, remoteEtag pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateSyncRemoteEtag, remoteEtag)
	return err
}
