// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureSyncDeviceIds = `-- name: EnsureSyncDeviceIds :execrows
UPDATE sync_config
SET device_id = CASE WHEN device_id IS NULL OR device_id = '' THEN $1 ELSE device_id END,
    dataset_id = CASE WHEN dataset_id IS NULL OR dataset_id = '' THEN $2 ELSE dataset_id END
WHERE id = 1
`

type EnsureSyncDeviceIdsParams struct {
	DeviceID  pgtype.Text
	DatasetID pgtype.Text
}

func (q *Queries) EnsureSyncDeviceIds(ctx context.Context, arg EnsureSyncDeviceIdsParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureSyncDeviceIds, arg.DeviceID, arg.DatasetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSyncConfig = `-- name: GetSyncConfig :one
SELECT id, server_url, username, password, auto_sync, last_sync_at, remote_etag, device_id, dataset_id, ai_settings_remote_etag FROM sync_config
WHERE id = 1
`

func (q *Queries) GetSyncConfig(ctx context.Context) (SyncConfig, error) {
	row := q.db.QueryRow(ctx, getSyncConfig)
	var i SyncConfig
	err := row.Scan(
		&i.ID,
		&i.ServerUrl,
		&i.Username,
		&i.Password,
		&i.AutoSync,
		&i.LastSyncAt,
		&i.RemoteEtag,
		&i.DeviceID,
		&i.DatasetID,
		&i.AiSettingsRemoteEtag,
	)
	return i, err
}

const updateSyncAiSettingsRemoteEtag = `-- name: UpdateSyncAiSettingsRemoteEtag :exec
UPDATE sync_config
SET ai_settings_remote_etag = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncAiSettingsRemoteEtag(ctx context.Context, aiSettingsRemoteEtag pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateSyncAiSettingsRemoteEtag, aiSettingsRemoteEtag)
	return err
}

const updateSyncConfigCredentials = `-- name: UpdateSyncConfigCredentials :exec
UPDATE sync_config
SET server_url = $1,
    username = $2,
    password = $3,
    auto_sync = $4
WHERE id = 1
`

type UpdateSyncConfigCredentialsParams struct {
	ServerUrl string
	Username  string
	Password  string
	AutoSync  bool
}

func (q *Queries) UpdateSyncConfigCredentials(ctx context.Context, arg UpdateSyncConfigCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateSyncConfigCredentials,
		arg.ServerUrl,
		arg.Username,
		arg.Password,
		arg.AutoSync,
	)
	return err
}

const updateSyncLastSyncAt = `-- name: UpdateSyncLastSyncAt :exec
UPDATE sync_config
SET last_sync_at = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncLastSyncAt(ctx context.Context, lastSyncAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateSyncLastSyncAt, lastSyncAt)
	return err
}

const updateSyncRemoteEtag = `-- name: UpdateSyncRemoteEtag :exec
UPDATE sync_config
SET remote_etag = $1
WHERE id = 1
`

func (q *Queries) UpdateSyncRemoteEtag(ctx context.Context, remoteEtag pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateSyncRemoteEtag, remoteEtag)
	return err
}
