// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    sync_id,
    title,
    description,
    status,
    priority,
    due_date,
    tags,
    is_daily,
    last_completed_date,
    reminder_time,
    remind_at
) VALUES (
    COALESCE(NULLIF($1::text, ''), gen_random_uuid()::text),
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, sync_id, title, description, status, priority, due_date, tags, remind_at, reminder_time, is_daily, last_completed_date, deleted_at, created_at, updated_at
`

type CreateTaskParams struct {
	SyncID            string
	Title             string
	Description       string
	Status            string
	Priority          string
	DueDate           pgtype.Date
	Tags              []byte
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
	RemindAt          pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.SyncID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.IsDaily,
		arg.LastCompletedDate,
		arg.ReminderTime,
		arg.RemindAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.RemindAt,
		&i.ReminderTime,
		&i.IsDaily,
		&i.LastCompletedDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, sync_id, title, description, status, priority, due_date, tags, remind_at, reminder_time, is_daily, last_completed_date, deleted_at, created_at, updated_at FROM tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.RemindAt,
		&i.ReminderTime,
		&i.IsDaily,
		&i.LastCompletedDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTasksForSync = `-- name: ListAllTasksForSync :many
SELECT id, sync_id, title, description, status, priority, due_date, tags, remind_at, reminder_time, is_daily, last_completed_date, deleted_at, created_at, updated_at FROM tasks
ORDER BY id ASC
`

func (q *Queries) ListAllTasksForSync(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listAllTasksForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.RemindAt,
			&i.ReminderTime,
			&i.IsDaily,
			&i.LastCompletedDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, sync_id, title, description, status, priority, due_date, tags, remind_at, reminder_time, is_daily, last_completed_date, deleted_at, created_at, updated_at FROM tasks
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR priority = $2::text)
ORDER BY created_at DESC, id DESC
`

type ListTasksParams struct {
	StatusFilter   pgtype.Text
	PriorityFilter pgtype.Text
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.StatusFilter, arg.PriorityFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SyncID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.Tags,
			&i.RemindAt,
			&i.ReminderTime,
			&i.IsDaily,
			&i.LastCompletedDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskDailyCompleted = `-- name: SetTaskDailyCompleted :exec
UPDATE tasks
SET status = CASE WHEN $1::boolean THEN 'done' ELSE 'todo' END,
    last_completed_date = CASE WHEN $1::boolean THEN $2::date ELSE NULL END,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL AND is_daily = true
`

type SetTaskDailyCompletedParams struct {
	Completed     bool
	CompletedDate pgtype.Date
	ID            int64
}

func (q *Queries) SetTaskDailyCompleted(ctx context.Context, arg SetTaskDailyCompletedParams) error {
	_, err := q.db.Exec(ctx, setTaskDailyCompleted, arg.Completed, arg.CompletedDate, arg.ID)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $1,
    description = $2,
    status = $3,
    priority = $4,
    due_date = $5,
    tags = $6,
    is_daily = $7,
    last_completed_date = $8,
    reminder_time = $9,
    remind_at = $10,
    updated_at = now()
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, sync_id, title, description, status, priority, due_date, tags, remind_at, reminder_time, is_daily, last_completed_date, deleted_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title             string
	Description       string
	Status            string
	Priority          string
	DueDate           pgtype.Date
	Tags              []byte
	IsDaily           bool
	LastCompletedDate pgtype.Date
	ReminderTime      pgtype.Time
	RemindAt          pgtype.Timestamptz
	ID                int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.Tags,
		arg.IsDaily,
		arg.LastCompletedDate,
		arg.ReminderTime,
		arg.RemindAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SyncID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.Tags,
		&i.RemindAt,
		&i.ReminderTime,
		&i.IsDaily,
		&i.LastCompletedDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
