// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: termphase.sql

package store

import (
	"context"
)

const hasCoursesForSemester = `-- name: HasCoursesForSemester :one
SELECT EXISTS(
    SELECT 1 FROM courses WHERE semester = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) HasCoursesForSemester(ctx context.Context, semester string) (bool, error) {
	row := q.db.QueryRow(ctx, hasCoursesForSemester, semester)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
