-- 002: tasks table (soft-delete + cross-device sync_id).

CREATE TABLE tasks (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id             text,
    title               text NOT NULL,
    description         text NOT NULL DEFAULT '',
    status              text NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done')),
    priority            text NOT NULL DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
    due_date            date,
    tags                jsonb NOT NULL DEFAULT '[]',
    remind_at           timestamptz,
    reminder_time       time,
    is_daily            boolean NOT NULL DEFAULT false,
    last_completed_date date,
    deleted_at          timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_tasks_sync_id ON tasks (sync_id)
    WHERE sync_id IS NOT NULL AND sync_id <> '';
