-- 003: courses + exams tables.

CREATE TABLE courses (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id              text,
    name                 text NOT NULL,
    day_of_week          integer NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time           time NOT NULL,
    end_time             time NOT NULL,
    location             text NOT NULL DEFAULT '',
    teacher              text NOT NULL DEFAULT '',
    color                text NOT NULL DEFAULT '#3B82F6',
    semester             text NOT NULL DEFAULT '',
    week_pattern         text NOT NULL DEFAULT '',
    semester_start_date  date,
    deleted_at           timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_courses_sync_id ON courses (sync_id)
    WHERE sync_id IS NOT NULL AND sync_id <> '';

CREATE TABLE exams (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id            text,
    course_name        text NOT NULL,
    exam_datetime      timestamptz NOT NULL,
    exam_end_datetime  timestamptz,
    location           text NOT NULL DEFAULT '',
    notes              text NOT NULL DEFAULT '',
    course_id          bigint REFERENCES courses (id) ON DELETE SET NULL,
    semester           text NOT NULL DEFAULT '',
    deleted_at         timestamptz,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_exams_sync_id ON exams (sync_id)
    WHERE sync_id IS NOT NULL AND sync_id <> '';
