-- 004: pomodoro tables (profiles + sessions + runtime state) + builtin profile seeds.

CREATE TABLE pomodoro_profiles (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        text NOT NULL UNIQUE,
    work_seconds                integer NOT NULL CHECK (work_seconds >= 60),
    short_break_seconds         integer NOT NULL CHECK (short_break_seconds >= 60),
    long_break_seconds          integer NOT NULL CHECK (long_break_seconds >= 60),
    sessions_before_long_break  integer NOT NULL CHECK (sessions_before_long_break >= 1),
    is_builtin                  boolean NOT NULL DEFAULT false,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE pomodoro_sessions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id       text,
    started_at    timestamptz NOT NULL,
    ended_at      timestamptz,
    session_type  text NOT NULL CHECK (session_type IN ('work', 'short_break', 'long_break')),
    task_id       bigint REFERENCES tasks (id) ON DELETE SET NULL,
    deleted_at    timestamptz
);

CREATE UNIQUE INDEX idx_pomodoro_sessions_sync_id ON pomodoro_sessions (sync_id)
    WHERE sync_id IS NOT NULL AND sync_id <> '';

CREATE TABLE pomodoro_runtime_state (
    id                 bigint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    phase              text NOT NULL DEFAULT 'work' CHECK (phase IN ('work', 'short_break', 'long_break')),
    remaining_seconds  integer NOT NULL DEFAULT 1500,
    total_seconds      integer NOT NULL DEFAULT 1500,
    is_running         boolean NOT NULL DEFAULT false,
    active_session_id  bigint,
    date_key           date NOT NULL,
    last_seen_at       timestamptz NOT NULL,
    interrupted        boolean NOT NULL DEFAULT false,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

INSERT INTO pomodoro_profiles
    (name, work_seconds, short_break_seconds, long_break_seconds, sessions_before_long_break, is_builtin)
VALUES
    ('default', 1500, 300, 900, 4, true),
    ('intense', 3000, 600, 1800, 3, true),
    ('relaxed', 1500, 600, 1200, 4, true)
ON CONFLICT (name) DO NOTHING;
