-- 005: semester context + term phase tables.

CREATE TABLE semester_context (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source         text NOT NULL,
    academic_year  text,
    term           text,
    term_label     text NOT NULL,
    start_date     date,
    current_week   integer CHECK (current_week IS NULL OR current_week >= 1),
    total_weeks    integer CHECK (total_weeks IS NULL OR total_weeks >= 1),
    refreshed_at   timestamptz NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source, term_label)
);

CREATE INDEX idx_semester_context_source_refreshed_at
    ON semester_context (source, refreshed_at);

CREATE TABLE term_phases (
    id                           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_id                      text,
    term_label                   text NOT NULL,
    phase_type                   text NOT NULL CHECK (phase_type IN ('teaching', 'exam', 'break')),
    start_week                   integer NOT NULL CHECK (start_week >= 1),
    end_week                     integer NOT NULL CHECK (end_week >= start_week),
    affects_courses              boolean NOT NULL DEFAULT true,
    affects_exam_notifications   boolean NOT NULL DEFAULT true,
    pomodoro_profile             text NOT NULL DEFAULT 'default',
    notification_rules           jsonb NOT NULL DEFAULT '{}',
    sort_order                   integer NOT NULL DEFAULT 0,
    deleted_at                   timestamptz,
    created_at                   timestamptz NOT NULL DEFAULT now(),
    updated_at                   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_term_phases_term_label_sort_order
    ON term_phases (term_label, sort_order);

CREATE UNIQUE INDEX idx_term_phases_sync_id ON term_phases (sync_id)
    WHERE sync_id IS NOT NULL AND sync_id <> '';
