-- 006: AI morning brief table.

CREATE TABLE ai_morning_brief (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          date NOT NULL UNIQUE,
    markdown      text NOT NULL,
    source        text NOT NULL CHECK (source IN ('ai', 'rule')),
    model         text NOT NULL DEFAULT '',
    generated_at  timestamptz NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_morning_brief_date ON ai_morning_brief (date);
